name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use the Python version required by your bot

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -t ./
          pip install awscli aws-sam-cli  # Ensure AWS SAM CLI is installed

      - name: Verify AWS S3 Bucket Secret
        run: echo ${{ secrets.AWS_S3_BUCKET }}

      - name: Package Lambda function
        run: |
          sam build
          sam package --template-file .aws-sam/build/template.yaml --output-template-file packaged.yaml --s3-bucket ${{ secrets.AWS_S3_BUCKET }}

      - name: Upload to S3
        run: aws s3 cp function.zip s3://id.thegrid.dev/lambdas/telegram_the_grid_bot/lambda.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1

      - name: Update Lambda function code from S3
        run: aws lambda update-function-code --function-name telegram_the_grid_bot --s3-bucket id.thegrid.dev --s3-key lambdas/telegram_the_grid_bot/lambda.zip --region eu-central-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-central-1
