name: Deploy to AWS Lambda

on:
  push:
    branches:
      - testing  # Set this to the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Set this to your Python version

      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            !~/.cache/pip/log
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt -t ./
          pip install awscli

      - name: Package Lambda function
        run: |
          zip -r function.zip . -x ".git/*" ".github/*" "*.zip"

#      - name: Upload to S3
#        run: aws s3 cp function.zip s3://id.thegrid.dev/lambdas/GridDigger/lambda.zip
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: eu-central-1
#
#      - name: Update Lambda function code from S3
#        run: aws lambda update-function-code --function-name telegram_the_grid_bot --s3-bucket id.thegrid.dev --s3-key lambdas/GridDigger/lambda.zip --region eu-central-1
#        env:
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          AWS_REGION: eu-central-1
